### ISSUE TITLE
To-Do for init.sql

### ISSUE THREAD

**Issue by jylee-git** [DriverUncle/TumpangMePlease#12]
To do list for init.sql:

- [ ] 1. Create trigger to remove from `Promo` if quota has reached 0.
- [ ] 2. Create trigger to ensure that bids.numPassengers < car.size
- [ ] 3. Create (trigger?) when driver/system selected winning bids, update all status of affected bids, and insert into scheduledRide

**Comment by jamessspanggg** [comment]
Add `highest_bid`, `number_of_bidders` into `advertisement` table
